import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Homepage from './Homepage';
import { useDispatch, useSelector } from "react-redux";
import Login from './Login';

export default function Home() {
  const user = useSelector(state=>state.user);
  /*const user = {
    id: 1,
    username: "Teste",
    profile_picture: "/img/tabosa.jpg"
  }*/
  return (
    <div className={styles.container}>
      <Head>
        <title>Whatsapp Web Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        user.id !== -1 ? 
        <Homepage user={user} /> :
        <Login />
      }
    </div>
  )
}
